### PR TITLE
Fixes

### LINKED ISSUE #5: Library doesn't work in IE due to Text() constructor
The Text object has no constructor in IE. Therefore the computeOverlayNodes function raises exceptions.

https://developer.mozilla.org/en-US/docs/Web/API/Text/Text

### LINKED ISSUE #7: Position is wrong on firefox
On Firefox, the "padding" style is not copied.

This is because on Firefox, the following happens:

```javascript
getComputedStyle(textarea).getPropertyValue('padding') // => ""
```

Only individual properties, such as `'padding-top'`, exist in Firefox

### PR DESCRIPTION
**Pull request by glebm**
1. Instead of calling `getComputedStyle` every time, call it once in the constructor, because `getComputedStyle` returns a "live" object. Adds a new `copyTextareaStyle` method.
2. When remembering the original textarea styles, use `style` instead of `getComputedStyle`, to avoid messing with priorities (if an original style was "", that lets CSS take over).
3. Do not `remove` nodes before appending / inserting them, it is not necessary.
4. Remove utility functions:

    1. Replaced `utils/flatten.js` with `Array.prototype.concat`.
    2. Removed `utils/getStyle.js`, no longer used after refactorings 1 and 2.
    3. Moved `utils/setStyle.js` into `textoverlay.js` as it was the only one left.

   Because modules generate quite a bit of overhead when transpiled, this also significantly reduces the size of `dist/bundle.min.js`, from 8.2 KiB to 5.2 KiB. 
5. Remove `main.js` as it only imported one module. Use webpack for exporting the global instead.
6. Use `document.createTextNode` instead of `new Text`. Fixes #5.
7. Do not use shorthand properties when copying styles from `getComputedStyle`. Fixes #7.
8. For minification, use uglify via webpack, like we do in textcomplete.

### CODE REVIEW

**Comment by glebm** [comment]
@yuku-t I've just noticed you're not "watching" this repo so you must have not received a notification about this PR.

**Comment by yuku** [comment]
Thanks for the patch and the notification 🌞  (now I'm watching this repo 😅 )

## Firefox
👍 

### Before
image

### After
image

## IE11
It seems `width` of `.textoverlay-wrapper` is wrong. (expected `510px` but `467px`) 🤔 

### Before
image

### After
image

**Comment by yuku** [comment]
> (expected 510px but 467px) 

Firefox
image

IE11
image

**Comment by yuku** [comment]
I think the issue mentioned above is not in the scope of this PR. So it is ok to merge this PR if you want.

**Comment by glebm** [comment]
Nice! I was literally just typing that 😄

**Comment by yuku** [comment]
Published textoverlay@0.1.5 to npm

**Pull request merged**
