### PR TITLE
Convert from Flow to TypeScript

### LINKED ISSUE #11: Use TypeScript instead of flow?
TypeScript is much more popular than flow, so I'm wondering if you'd accept a PR converting this project to TypeScript?

### PR DESCRIPTION
**Pull request by glebm**
Adds source linter and auto-formatter (on build).
Renames the `dist/` files for clarity.

Resolves #11

### CODE REVIEW

**Comment by yuku** [comment]
@glebm Thanks! Do you mind if I add you to collaborators of this repo?

**Comment by glebm** [comment]
Sure! By the way, textoverlay is now used here https://github.com/orlandohill/waxeye/pull/83, it's a perfect fit and a brilliant idea, thank you!

**Comment by yuku** [comment]
Yey 🎉 Feel free to add your name to package.json.
Do you need ownership of npm package too?

**Comment by glebm** [comment]
Sure, if that's OK with you, thanks!

**Comment by yuku** [comment]
Done 🕺 

image

**Pull request merged**
